"""Vedic astrology warm-white color palette constants."""

# Base backgrounds
BG_LIGHT = "#FAFAF7"
BG_PANEL = "#FFFFFF"
BG_CARD = "#FFFFFF"
BG_INPUT = "#FFFFFF"
BG_HOVER = "#EDE5D8"
BG_PARCHMENT = "#FDF5E6"
BG_BAR = "#F5F0E8"

# Accents
SAFFRON = "#D4760A"
MAROON = "#8B1A1A"
EMERALD = "#1E8449"
CRIMSON = "#C0392B"
OCEAN_BLUE = "#2980B9"

# Text
TEXT_PRIMARY = "#2C2C2C"
TEXT_SECONDARY = "#555555"
TEXT_MUTED = "#888888"

# Borders
BORDER_DEFAULT = "#D4C5B0"
BORDER_LIGHT = "#E0D6C8"
BORDER_ACTIVE = "#D4760A"

# Status
STATUS_SAFE = "#D5F5E3"
STATUS_DANGER = "#FADBD8"
STATUS_HOLD = "#FDEBD0"

# Chart
CHART_BG = "#FDF0D5"
CHART_GRID = "#8C7B65"
CHART_GRID_LK = "#8B0000"

# Highlights
HIGHLIGHT_ACTIVE = "#FFF3E0"
HIGHLIGHT_SELECTED = "#FEF6EC"
